### ISSUE TITLE
question

### ISSUE THREAD

**Issue by vsrdharca** [RodolfoPichardo/LinKernighanTSP#6]
@RodolfoPichardo 

Hello - Thank you for this implementation.  I am evaluating using this on a large list (50,000) of building structures to determine the shortest route order.  I have lat and longitude coordinate list.  
1.) Could I use GEO for EDGE WEIGHT TYPE and provide the lat & long values?  
2.) If I use EUC_2D how would I convert the lat long to the x, y coordinate system - what would I use as a base ref to compute x, c? 
3.) Do you have any metrics on run time for such large lists?

I appreciate your help.  Thank you for your time.

**Comment by RodolfoPichardo** [comment]
Hi @vsrdharca,

1) Currently only EUC_2D has been implemented. Implementing GEO should not be difficult, however, I am not able to do it this weekend, you are welcome to change the code and submit a PR though.

2) Since, EUC_2D is two dimensional and the coordinate system that you are proposing is three dimensional it is impossible to convert exactly, however, if the region that you are evaluating is small enough (e.g. a city, state, or a small country) you should be able to convert you coordinates with reasonable precision.

3) No, I have never used it for problems of that magnitude. One neat feature of this program is that you should always be able to get a result (even if the execution does not complete - see issue #5).

**Comment by vsrdharca** [comment]
@RodolfoPichardo Thank you so much for getting back to me. 

for #2 is the below logic for transformation from Geo coordinates and to EUC_2D OK?  The country under consideration is small.
    var lat = DegtoRad (latlong.Latitude);
    var lon = DegtoRad (latlong.Longitude);
    var x = earthRadius * Math.cos(lat)*Math.cos(lon);
    var y = earthRadius * Math.cos(lat)*Math.sin(lon);

**Comment by RodolfoPichardo** [comment]
I don't know how you got that formula, but it seems to be producing the right results. Keep in mind that I tested it with a -very- limited test data.

**Comment by vsrdharca** [comment]
@RodolfoPichardo 

Would you implement the conversion another way?

**Comment by RodolfoPichardo** [comment]
@vsrdharca 

What I had in mind was more complex (and probably less precise). I like your solution better.
